SECRET_KEY = 'you-will-never-guess'
DEBUG=True
MONGODB_DB = 'fakebook36'
MONGOLAB_URI = 'mongodb://<dbuser>:<dbpassword>@ds159235.mlab.com:59235/fakebook36'
HOSTNAME = 'https://fakebook36.herokuapp.com/'
UPLOAD_FOLDER = '/home/ubuntu/workspace/flaskbook/static/images'
STATIC_IMAGE_URL = 'images'
AWS_BUCKET = 'fakebookbackend'
AWS_CONTENT_URL = 'https://s3-us-west-2.amazonaws.com'